### ISSUE TITLE
Questions on Lines 98 and 102

### ISSUE THREAD

**Issue by Nosh21** [yaboiwierdal/frencharticleanalysis#1]
Al,
I noticed that you included a break on line 102. Why is that? If you chose to use a for loop, it would imply that you'd want to make use of an iterative process. So you'd want to print out the items of the suggested words list until it reaches the requested amount. However, putting a break on line 102 means that the entire for loop will cease after a single entry in the suggested words list is printed.

Also, what is the objective of the if block on line 98? If the length of the suggested words list is greater than the amount we requested, why exactly are we decrementing the requested amount variable? It's very likely that the amount of suggested words would be greater than the requested amount to begin with, but even if it wasn't, I don't quite get the point of decrementing the number of words your user wants, which should remain constant.
Best,
Nosh21

**Comment by yaboiwierdal** [comment]
Nosh,
     You're right about both things. I think line 102 just slipping in somehow, perhaps I accidentally pasted it. As for line 98, the ">" should be a "<". With that, the point of the line was to resolve an IndexError issue that was arising if you requested more words than were in the "suggested_words_list" list. I'll make those corrections. 
Thanks,
Alex
